services:
  px4-ros-rerun:
    image: px4-ros-rerun
    container_name: px4-ros-rerun
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    network_mode: host
    pid: "host"
    ipc: "host"
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - RR_WEBVIEWER_PORT=9090
    env_file: .env
    volumes:
      - ../:/ws
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - /dev/dri:/dev/dri:cached
    security_opt:
      - seccomp:unconfined